eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

server:
  port: 8086

spring:
  application:
    name: feign-consumer

feign:
  hystrix:
    enabled: true